language: generic
sudo: false

install:
  - sudo apt-get install -y make m4 texlive-xetex
  - curl -L -o pandoc.deb https://github.com/jgm/pandoc/releases/download/2.5/pandoc-2.5-1-amd64.deb
  - sudo dpkg -i pandoc.deb

script:
  - make
  - make pdf
  - make clean
