name: Build

on:
  - pull_request
  - push

jobs:
  build-and-test:
    strategy:
      fail-fast: true

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install system dependencies
        run: sudo apt-get install pandoc make texlive-full

      - name: Build
        run: make
